### PR TITLE
switch to "windows-headers" dub package for win32 support

### PR DESCRIPTION
**Pull request by gerdus**

### CODE REVIEW

**Comment by jpf91** [comment]
Thanks. Starting with DMD 2.070 these headers are included in druntime: https://github.com/D-Programming-Language/druntime/tree/master/src/core/sys/windows

`windows-headers` is still required for older compilers. I wonder whether we should use the druntime bindings for newer dmd compilers `static if (__VERSION__ >= 2070) import core.sys.windows.* else import windows.*`. This would probably require cairoD users to also use the `core.sys.windows` bindings. Maybe I should add a version statement `UseDruntimeWinAPI` to leave this decision to the users.

**Comment by jpf91** [comment]
Looks like dub doesn't support platform suffixes for the dependencies field:
https://github.com/D-Programming-Language/dub/issues/218

This should probably work:
```json
	"configurations": [
		{
			"name": "static-custom-windows",
			"targetType": "staticLibrary",
			"platforms": ["windows"],
			"dependencies": {"windows-headers": "~>1.0.1"}
		},
		{
			"name": "static-custom-posix",
			"targetType": "staticLibrary",
			"platforms": ["posix"],
			"dependencies": {"x11": "~>1.0.9"}
		},
		{
			"name": "unittest",
			"targetType": "executable",
			"sourceFiles": ["unittest.d"],
			"libs": ["cairo"],
			"versions": ["CairoPNG"]
		}
    ]
```

**Comment by gerdus** [comment]
My preference is to just plain depend on `windows-headers` until the majority of users have switched to 2.070 and then switch to the druntime version. Luckily switching between bindings is easy to do by hand for users so I think err-ing on the side of "just works" is good.

**Comment by jpf91** [comment]
OK. I'll merge as soon as the Travis CI tests pass. (You have to modify dub.json as explained above).

**Comment by jpf91** [comment]
Thanks!

**Pull request merged**
